# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git)
plugins=(git node brew bundle cap gem github osx rails rails3 ruby rvm svn textmate)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/Users/shirui/bin

# alias
alias cls='clear'
alias ll='ls -l' 
alias lm='ls -al'
#alias rm='rm -i'
alias h='history'
alias cp='cp -i'
alias mv='mv -i'
alias mysql=/usr/local/mysql/bin/mysql
alias mysqladmin=/usr/local/mysql/bin/mysqladmin

##
# Your previous /Users/shirui/.bash_profile file was backed up as /Users/shirui/.bash_profile.macports-saved_2012-04-20_at_10:47:52
##

# MacPorts Installer addition on 2012-04-20_at_10:47:52: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:/data/work/src/android-sdk-macosx/platform-tools:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

export CLASSPATH=$CLASSPATH:/Users/shirui/Develop/junit4.10/junit-4.10.jar

alias ares="cd /Users/shirui/Develop/ares && rsync -Cavz --exclude='.git/' --exclude='*.swp' svn/Resources/ '/Users/shirui/Library/Developer/Xcode/DerivedData/ares-epjlnudmgpfprocnthpbyaaagpie/Build/Products/Debug-iphonesimulator/ares.app/' && ios-sim launch '/Users/shirui/Library/Developer/Xcode/DerivedData/ares-epjlnudmgpfprocnthpbyaaagpie/Build/Products/Debug-iphonesimulator/ares.app/'"

export PS1='%{$fg[magenta]%}%(?..%?%1v )%n%{$reset_color%}@%{$fg[green]%}%m%{$reset_color%} %{$fg[cyan]%}%c%{$reset_color%} ${vcs_info_msg_0_}% $(getPwd)% $(git_branch)% $(git_since_last_commit)# '
#export PS1="[\[\033[1;32m\]\w\[\033[0m\]] \[\033[0m\]\[\033[1;36m\]\$(git_branch)\[\033[0;33m\]\$(git_since_last_commit)\[\033[0m\]$ " 

function getPwd {
    echo "("`pwd`")"
}

function git_branch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return;
    echo "("${ref#refs/heads/}") ";
}

function git_since_last_commit {
    now=`date +%s`;
    last_commit=$(git log --pretty=format:%at -1 2> /dev/null) || return;
    seconds_since_last_commit=$((now-last_commit));
    minutes_since_last_commit=$((seconds_since_last_commit/60));
    hours_since_last_commit=$((minutes_since_last_commit/60));
    minutes_since_last_commit=$((minutes_since_last_commit%60));
    
    echo "${hours_since_last_commit}h${minutes_since_last_commit}m ";
}
