--
-- Created by
-- User: wancheng@playcrab
-- Date: 12-5-16
-- Time: 下午12:04


TipChinese={
    ["IntroWugongPopupTitle"] ="武功介绍",

    ["IntroCanpianPopupTitle"] ="武功残章介绍",
    ["DuomijiGetCanZhangDes"] ="恭喜掌门，果然在对手身上搜出了#1，距离获得#2又近了一步！",
    ["CommonGetCanZhangDes"] ="意外之喜!禀报掌门,发现了#1，哈哈，#2已经唾手可得了！",
    ["GetQiyuCanZhangDes"] ="#2重现江湖！禀报掌门，这是#1，其他残章下落也有可靠消息，可立即前往夺取。",
    ["CanpianCommonDescription"] ="#1是#2的一部分残章，收集齐#3份残章之后，通过拼合即可得到。",
    ["LostDuoMijiFailPopupTitle"] = "夺取残章失败",
    ["BattleLostDuoMijiFailPopupDes"] ="败给对手，未能获取残章。",
    ["EnemyHaveNothDuoMijiFailPopupDes"] ="启禀掌门，其他人抢先一步，夺走了对方的残章。",
    ["EnemyEscapeDuoMijiFailPopupDes"] ="启禀掌门，对手战败后立即逃之夭夭，追赶不及，未能获得残章。",
    ["CurrentHaveNum"] ="当前拥有数量： ",
    ["DuoCanpianPopupTitle"] ="抢夺武功残章",
    ["DuoCanpianOKPopupTitle"] ="成功夺得武功残章",
    ["DuoCanpianFailedPopupTitle"] ="抢夺武功残章失败",
    ["AssembleMijiOkTitle"] ="成功拼合武功秘籍" ,
    ["ShopGoodsIntroPopupTitle"]="道具信息",
    ["MoneyNotEnoughTitle"] = "购买失败",

    ["SellGetMoneyDes"] = "掌门,出售成功,您获得#1银两",
    ["GemNotEnoughDes"] = "掌门,您的#gem不足，通过充值可获得#gem。",
    ["AlreadyCanbai"] = "掌门，您今日已经参拜过了，请明日再来。",
    ["MaxCanbai"] = "掌门,您已经获得秘籍无需参拜。",
    ["LvlNotEnoughTitle"] = "等级不够",
    ["LvlNotEnoughDes"] = "掌门,需要等级达到#1级，请继续努力。",
    ["NeedToolWish"] = "掌门,需要#1才能进行许愿.",
    ["NeedVipWish"]="今日许愿次数已用完,达到VIP#1可以获得额外次数.",
    ["WishFinish"]="今日许愿次数已用完,请掌门明日再来.",
    ["WishNotTitle"]="许愿次数不足",
    ["WishSucGet"]="恭喜掌门,您获得#1个#2魂魄",
    ["WishNotCan"]="无法许愿",
    ["WishNotSelect"]="掌门，此弟子不能进行许愿",
    ["WishSelectPeople"]="甲级弟子才能被选择进行许愿",
    ["JingLianItem"]="掌门,闯江湖时可以获得精炼材料!",
    ["JingLianLeftTip"]="掌门,请先放入左侧的精炼材料",
    ["ChuangFailTitle"] = "闯关失败",
    ["SellTipTitle"] = "出售装备",
    ["SellTipAdanceDes"] = "掌门,是否出售高级装备!",
    ["SellTipDes"] = "您确定要出售吗?",
    ["SellNotEquip"] = "掌门,弟子使用中的装备不能出售!",
    ["LastOne"] ="最后一个" ,
    ["AccidentAwardTitle"] = "意外收获",
    ["AccidentAwardTip"] = "恭喜掌门，您得到了" ,
    ["equipmentInfoTitle"] = "装备信息",

    ["ChuangongNoPeople"] = "当前没有散功弟子",
    ["ChuangongNoLvlPeople"] = "等级大于1级未上阵的弟子，才能散功",
    ["ChuangongOK"] = "恭喜掌门,弟子传功成功",
    ["ChuangongBuyTool"] = "掌门,请购买传功丹",
    ["ChuangongNeedCard"] = "掌门,请选择散功弟子",
    ["ChuangongMax"] = "掌门，此弟子已达当前等级上限",
    ["CanWuNo"] = "没有可选择的参悟武功",
    ["CanWuSelectMax"] = "最多只能选择5个参悟武功",
    ["ServerFailTitle"] = "通信失败",
    ["ServerFailDes"] = "很遗憾，通信出错了请刷新!",
    ["skillInfoTitle"] = "武功信息",
    ["peopleInfoTitle"] = "人物信息",
    ["canzhang"] = "残章之",
    ["PeopleCardInfoTitle"] = "弟子信息",
    ["SoulCardInfoTitle"] = "魂魄信息",
    ["EquipCardInfoTitle"] = "装备信息",
    ["WugongCardInfoTitle"] = "武功信息",
    ["WugongNotCanwu"] = "掌门,此等绝学无需参悟!",
    ["NotSellTeamCard"] = "上阵弟子不能出售!",
    ["Soullist"] = "收集足够数量的人物魂魄，即可招募该人物。",
    ["Peoplelist"] = "传功、培养弟子，提升实力。",
    ["Wugonglist"] = "参悟武功，提高攻击、弟子属性。",
    ["chineseNumArr"] = {"一","二","三","四","五","六","七","八","九"},
    ["NeedSelectOnePinzi"] = "请选择至少一个品质",
    ["NeedSelectOneKind"] = "请选择一个类别",
    ["EquipQianghuaMax"] = "已经达到当前强化最大等级",
    ["FinishEmployCount"] = "今日招募次数已用完",
    ["UseToolOk"] = "使用了道具",
    ["BuyToolOk"] = "成功购买",
    ["BuyToolTipOk"] = "掌门,购买#1成功!",
    ["ToolCanNotUse"] = "今日道具增加体力已达到上限",
    ["ToolCanNotUseYuanQi"] = "今日道具增加元气已达到上限",
	["equipmentBottomTipHash"] = {attack = "增加攻击力", defense = "增加防御力" ,magic="增加内力值", health="增加生命值"},
    ["alreadyHaveCanzhang"] = "已拥有该残章" ,
    ["needCanzhangEachOne"] = "拼合需要集齐每种残章各一个"  ,
    ["freeRecruitTodayCountOver"]  = "今日免费次数已用完"   ,
    ["freeRecruitCountWithMax"]  = "今日#1/#2次免费机会"     ,
    ["awardGem"] = "掌门,恭喜你获得#1#gem奖励!",
    ["levelAwardGemVip"]="掌门,恭喜获得VIP#1级以及#2#gem!",
    ["levelAwardByOrder"]="掌门，请按顺序领取奖励!",
    ["EquipQianghuaSuc"] = "恭喜掌门,装备强化成功",
    ["WugongCanwuSuc"] = "恭喜掌门,武功参悟成功",
    ["WugongcanwuFail"] = "很遗憾此次武功参悟失败",
    ["WugongCanwuMax"] = "启禀掌门，该武功已参悟至最高级别",
    ["freeRecruitCountWithoutMax"]  = "今日#1次免费机会",
    ["attackOne"] = "单体攻击",
    ["attackAll"] = "群体攻击",
    ["extraMoneyReward"]  = "\n    掌门，发财了！意外收获#1【银两】！",
	["taskMaxUnlockNeedVipLevel"] = "清除江湖次数最低需要VIP3级!",
    ["vipNotEnoughDes"]="掌门,需要VIP#1级，即可。",
    ["vipNotEnoughBuyDes"]="掌门,只有达到VIP#1才能购买次礼包,快去充值吧",
	["noticeWhenStaminaFull"] = "体力满",
	["noticeWhenEnergyFull"] = "元气满",
	["noticeWhenBeAttacked"] = "被攻击" ,
	["noticeWhenFriendGift"] = "好友礼物",
	["weibobangding"] = "绑微博，与韦小宝猜拳，发微博得银两。",
	["weibodenglu"] = "绑定微博过期，需重新登录",
	["weiboyibangding"] = "已绑定微博",
	["noti_energy_full"] = "禀报掌门，弟子们的元气已恢复，还请掌门带领弟子挑战他人。",
	["noti_stamina_full"] = "禀报掌门，弟子们的体力已恢复，还请掌门带领弟子继续闯荡江湖。",
	["notexistfreedizi"] = "没有多余空闲弟子",

    ["LunjianCommonTip"] ="击败所有对手让本门立于论剑之巅!\n排名越前，积分奖励越多！",
    ["LunjianShenghuiTip"] ="只有在论剑中证明了自己的强者，才能参加盛会！\n盛会积分奖励更高！"  ,
    ["LunjianTitleCommon"] = "第#2届#1第#3场"  ,
    ["LunjianTitleShenghui"] = "第#2届武林盛会之#1"      ,
    ["LunjianTitleUnion"] = "武林论剑大会"      ,

    ["LunjianWinTip"] = "论剑获胜，排名升至第#1名！",
    ["ActiveJianghuNot"] = "启禀掌门，您还没闯完此江湖，不能领取",
    ["LunjianLostTip"] = "胜败乃兵家常事，再战一场吧~",
	["mijichoudi"] = "奇遇仇敌",
    ["changeCardTip"] = "#1已经使用了!",
    ["tipFailTitle"] = "提示",
	["lunjianchoudi"] = "论剑仇敌",
    ["OpenBoxtip"] = "恭喜掌门，获得#1个#2!",
    ["GetSomeThTip"] = "获得数量#2的#1",
    ["DianBoExp"] = "#1点经验。",
    ["DianBoBeforeTalk"] = "掌门麾下弟子天赋出众，老夫手痒难耐，越权指点一二，还望掌门海涵",
    ["DianBoAfterTalk"] = "掌门弟子们果然聪慧，一点就透,还请教掌门确认此次点拨成果",
    ["DianBoFinishTalk"] = "无需客气。你的弟子们大有长进，还要再接再厉。就此别过，以后有缘再见",
    ["DianBoTipDes"] = "点拨倒计时结束后，拜谢前辈，即可让所有上阵弟子获得#1点经验。",
    
	["ChuanshuEmpty"] = "禀报掌门，本门尚未接到传书",
 
    ["LunjianGetPeiyangdan"] = "恭喜掌门，此次炼丹获得#1枚培养丹。"   ,
    ["LunjianUsePeiyangdanTip"] = "培养弟子，激发潜能，获得更强实力！"  ,
    ["ZijueMaxlvl"] = "掌门,掌门诀的等级不能超过当前门派等级!",
    ["ZijueSelect"] = "掌门，请选择弟子后者魂魄",
    ["ZijueUplvl"] = "恭喜掌门,#1提升到#2级!",
    ["ZijueUpExp"] = "恭喜掌门,#1魄力增加!",
    ["ZijueSure"] = "您选择了消耗甲乙弟子或魂魄，确定吗？",
    ["ZhenqiSure"] = "您选择了消耗甲乙真气，确定吗？",
    ["GetSoulIconDes"] = "收集足够数量的魂魄后，通过招募，获得弟子；通过突破，增加弟子潜力。" ,
    ["GetSoulIconPopupDes"] = "恭喜掌门获得 #1 #2个！"    ,
    ["GetSoulIconPopupTip"] = "弟子魂魄列表中,查看当前拥有全部魂魄。",

	["friendEmptyDes"] = "点击加好友就可以查找其他门派",
	["enemyEmptyDes"] = "本门暂时还没有仇敌",
	["followEmptyDes"] = "在仇敌内选择一个门派关注吧",
    
    ["ResetTiLiDes"] = "花费#1#gem可立即恢复#2点体力",
    ["ResetCountDes"] = "已恢复#1/#2次",
    ["ResetVipDes"] = " VIP#1每天可恢复#2次。",
    ["ResetYuanQiDes"] = "花费#1#gem可立即恢复#2点元气",
    ["ResetCountFinishDes"] = "掌门,今日恢复次数已用完",
    ["ResetTiLiOkDes"] = "恭喜掌门,恢复#1点体力!",
    ["ResetYuanQiOkDes"] = "恭喜掌门,恢复#1点元气!",
    ['UseJiaohuajiTip'] ='已吃#1只（最多#2只）',
    ['UseBuyuandanTip'] ='已吃#1颗（最多#2颗）',
    ['VipExtraCountDan']='成为VIP#1每天可以吃#2颗补元丹',
    ['VipExtraCountJi']='成为VIP#1每天可以吃#2只叫花鸡',
    
    ["OpenNormalNeedKey"] = "掌门,需要\"#1\"才能开启!",
	["TupoDescText"] = "使用弟子本人的魂魄可突破层次，每突破一层，获得#1点潜力。",
    ["RepeatName"] = "该名称已经被使用，请重输入新名称",
    
    ["XueZhanFightDes"] = "已守卫#1场，剩#2场机会",
    ["xueZhanSelectDes"] = "您昨天单场守卫最高得星#1，可提前为一项属性",
    ["xueZhanStarNotEnough"] = "掌门还需星星#1枚，请加油",
    ["XueZhanCountFinish"] = "今日已用完守卫次数，请掌门明日再来~",
    ["XueZhanCountNum"] = "已闯过#1关",
    ["XueZhanFiveGuanDes"] = "#1~#2关得星数:#3",
    ["XueZhanFiveGuanBigDes"] = "超出今天最佳成绩#1颗星，获得:",
    ["XueZhanFiveGuanNotDes"] = "未超出今天最佳成绩(#1星),无奖励",
    ["XueZhanRankIng"] = "排名正在统计中,请掌门静候佳音!",
    ["XueZhanNotRank"] = "禀报掌门，目前没有排名!",
    ["XueZhanGuanDes"] = "本次血战结束，您的弟子们闯过#1关。",
    
    ["WorldBossStarTime"] = "#1:#2",
    ["XueZhanGuanDes"] = "本次血战结束，您的弟子们闯过#1关。"   ,
    ["WeiboTitle"] = "绑定微博",
    ["WeiboDes"]="掌门,微博功能即将开放敬请期待!",
    ["QualityWenziArr"] ={"丁","丙","乙","甲"},
    ["DupOtherDes"]="掌门，你在别的设备上线了",
    ["FightDataError"]="掌门，战斗出错了！",

    ["ActGongceExtraSoulGetTip"] = "恭喜掌门获得活动额外魂魄."   ,
    ["ActGongceExtraSoulGetDesOne"] = "#1魂魄(#2) #3 个"   ,
    ["ActGongceExtraSoulGetDesMult"] = "#1魂魄(#2) #3+#4 个",

    ["YuanfenEquipLack"]='启禀掌门，#1乃是弟子梦寐以求之物，请您留心搜寻。',
    ["YuanfenEquipNotInUsing"]='#1乃是弟子心之所向，还请掌门赐予弟子。',
    ['YuanfenEquipActive']='感谢掌门赐我#1, 吾必尽己所能光大本门！',
    ['YuanfenHeroLack']='弟子与#1神交已久，若能携手必能所向匹敌。',
    ['YuanfenHeroNotInTeam']='#1与我同为掌门门下，但并未上阵，不能与之并肩而战，甚是遗憾！',
    ['YuanfenHeroActive']='#1与我配合无间，我们一起并肩战斗能使我战力提升',
    ['YuanfenEquipWrongHero']='#1暴殄天物，所持有的#2正是弟子心头所好，还望掌门赐予弟子。',
    ['ChenghaoOnlyEffectTo']='加成效果只对【#1】称号有效',
    ['HourUnit']='小时',
    ['Forever']='永久',
    ['RankToRank']='#1至#2',
    ['ChenghaoGetCongratu']='恭喜掌门获得新称号',
    ['ChenghaoUpgradeCongratu']='恭喜掌门称号升级',

    ['RichGodTimeTip']='财神显灵#1天，#gem变#gem！你还有#2次机会！',
    ['RichGodTimeLeft']='#1天#2小时#3分',

    ['RechargeIntroduction1']='充#1，您将获得#2#gem。',
    ['RechargeNum']='充#1',
    ['PhoneNotRight'] = "请输入正确的手机号",
    ['LanghuanCountLeft']='今日剩#1次' ,
    ['LanghuanTimeLeft']='活动结束时间：#1天',
    ['LanghuanTimeLastDay']='最后一天',
    ['LanghuanResultDes']='在段誉的帮助下获得了:' ,
    ['LanghuanCountUseUp']='今日次数已用完' ,

    ['chongjiarea_lvlTipTxt'] = '升级有奖励，#gemVIP。每次升级均可获赠10#gem！某些等级还能获得VIP资格，领取更多#gem',
    ['chongjiarea_taskTipTxt'] = '闯荡江湖扬名立万，现在完成指定关卡任务即可领取#gem，号令群雄指日可待！',

    ['item_award_desTxt'] = '为感谢您的支持，删档内测期间，每天登录就送您2000#gem，欢迎提交bug或建议。',

    ['fanyuanbaotps_chargeReturnTip'] = '活动期间，所有充值都将额外获赠#1倍价值的#gem。',
    ['fanyuanbaotps_bottomTip'] = '充值越多，返值越高。最高可每天返#1#gem。',

    ['gem']='#gem',
    ['NormalGemName']='元宝',
    ['QQGemName']='黄金',
    ['ZhaomudiziMsg1']="节日，付费万里挑一遇魂魄，返还100#gem",
    ['ZhaomudiziMsg2']="节日，付费百里挑一遇魂魄，返还30#gem~",
    ['SuccRechargeTip']='成功充值#1#gem',
    ['RechargeFailTip1']='充值信息尚未到账，点击重试按钮继续检查。如果您取消检查，充值信息到账后下次进入游戏时#gem数量会自动刷新。',
    ['WelcomeGodTip1']='恭喜#1掌门 迎财神得#2#gem',
    ['WelcomeGodTip2']='#1掌门迎财神得#2#gem（大爆）！',
    ['GodGambleTip']='财神感觉到了你的虔诚，将你献上的#1#gem变成了#2#gem！',
    ['FanyuanbaoIntroTip1']='充值累计#1元即可每日获得#2#gem，持续#3天。充值越多返值越高。最高每天返#4#gem',
--    ['FanyuanbaoIntroTip1']='充值累计达到#1元即可每日获得#2#gem，持续#3天。充值越多，返值越高。最高每天返#4#gem。',
    ['FanyuanbaoIntroTip2']='为感谢各位掌门，活动期间充值累计#1元以上(最高至#2元)都将获赠#3倍价值的#gem。',
    ['FanyuanbaoEveryDay']='每日可返#1#gem。',
    ['FanyuanbaoTip11']="恭喜掌门，每天可以从聚宝盆里领一次#gem。目前已领#1，一共还可以领#2。",
    ['FanyuanbaoTip12']='根据掌门之前充值的#1元，聚宝盆今天返给您#2#gem！',
    ['FanyuanbaoTip13']='\n所有#gem已经领完，活动结束！',
	['NoEnoughGem'] = "#gem不足",
	['NoEnoughGemDesc'] = "您的#gem不足，首次充值可获得双倍#gem！",
    ['HelpConfigJianghuDesc']="带领弟子闯荡江湖，江湖中有大大小小的事件，每一个事件下都需要对付很多波敌人，从他们身上能得到经验、银两甚至宝贵的道具，每个事件的难度不同可挑战次数也不同，次数消耗完可通过#gem来补充。",
	['InfoMenpaiming'] = "门派名",
	['InfoMenpaiLevel'] = "等级",
	['InfoMenpaiExp'] = "威望",
	['InfoMenpaiDizi'] = "上阵弟子",
	['energy'] = "元气",
	['money'] = "银两",
	['stamina'] = "体力",
	['InfoNextTiliRecover'] = "下一点体力恢复",
	['InfoTotalTiliRecover'] = "全部体力恢复",
	['InfoNextYuanqiRecover'] = "下一点元气恢复",
	['InfoTotalYuanqiRecover'] = "全部元气恢复",
    ['DoubleGem']='#gem翻倍',
    ['PointsLackStaminaTipDes']='掌门，您的体力不足，不能继续闯江湖。要不要吃只叫花鸡，能恢复8点体力哦！',
    ['PointsLackYuanqiTipDes'] ='掌门，您的元气不足，不能继续闯江湖。要不要吃只补元丹，能恢复8点元气哦！',
    ['FirstRechargeDoubleTip']='首次充值得的#gem将翻倍\n一旦错过将不再有',
    ['MillionMoney']='百万银两',
    ['100Peiyangdan']='100培养丹',

    ['MingShanNeedOpenTip']='掌门,此处尚未开启',
    ['MingShanFightFinishTip']='掌门,此处宝藏已经探取',
    ["MingShanMaxUnlockNeedVipLevelTip"] = "清除名山战斗次数最低需要VIP3级!",
    ["MingShanCanNotGetAward"] ="掌门,不能领取宝箱",
    ['SaodangExtra']='意外获得：',
    ['CardRecordQuality'] = '#1是#2级品质,',
    ['CardRecordLevel']='#1等级为#2,',

    ['SiguoyaDoingTip']='掌门,此弟子在思过崖暂不能传功',
    ['SiguoyaNeedTip']='等级达到#1级以上的弟子可以修炼天赋武功',
    ['GiftUseLevelLimit']='达到#1级可以使用',
    ['LevelNum']='#1级',
    ['ChangeDiziZhenqi']='更换弟子真气',
    ['AlreadyHasSameZhenqi']='不能装备两个同类型的真气',
    ['MingShanLockTip'] = '闯过#1后开启',
    ['MingshanChenghaoDes']='通过【#1】\n可获得称号【#2】',
    ['MingshanTopLabel']='江湖传言魔教搜集众多宝藏藏于各地名山之中，并派高手镇守。此消息一出，引起江湖轩然大波，诸多门派前去探宝却铩羽而归……',
    ['MingshanCountFull']='该敌人已被彻底击败，无法挑战。',
    ['MingShanCountLimitTitleVip']='无法挑战',
    ['MingShanCountLimitTitle']='达到今日挑战次数上限',
    ['MingShanCountReset']='掌门,又可以重新挑战了',
    ['OpenZhenqiNeedLevel']='弟子达到#1级时解锁下一个真气格'  ,
    ['MingShanNotOpenTip'] = '掌门,需要闯江湖才能开启',
    ['FindOutMingshan']='发现【#1】入口！',
    ['ZhenyuanNeed']='需真元#1',
    ['ShopShanChenTip'] = '商场',
}
